DROP TABLE IF EXISTS student_points CASCADE;

DROP TABLE IF EXISTS student_achievements CASCADE;

DROP TABLE IF EXISTS achievements CASCADE;

DROP TABLE IF EXISTS recommendations CASCADE;

DROP TABLE IF EXISTS student_skills CASCADE;

DROP TABLE IF EXISTS resource_tags CASCADE;

DROP TABLE IF EXISTS tags CASCADE;

DROP TABLE IF EXISTS student_interactions CASCADE;

DROP TABLE IF EXISTS resource_ratings CASCADE;

DROP TABLE IF EXISTS student_progress CASCADE;

DROP TABLE IF EXISTS student_answers CASCADE;

DROP TABLE IF EXISTS questions CASCADE;

DROP TABLE IF EXISTS resources CASCADE;

DROP TABLE IF EXISTS modules CASCADE;

DROP TABLE IF EXISTS courses CASCADE;

DROP TABLE IF EXISTS student_profiles CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS interaction_type;

DROP TYPE IF EXISTS progress_status;

DROP TYPE IF EXISTS resource_type;

DROP TYPE IF EXISTS user_role;